---

- name: Include Debian install steps
  include_tasks: debian_repo.yaml
  when: ansible_os_family == 'Debian'

- name: Include RedHat EPEL repo installation steps
  include_tasks: rhel_epel.yaml
  when: ansible_os_family == 'RedHat'

- name: Include RedHat pgEdge repo installation steps
  include_tasks: rhel_repo.yaml
  when: ansible_os_family == 'RedHat'
